// Prime 131 Wine App — data
// Structure scale: 1 (lowest) to 5 (highest) for sweetness, acidity, tannin, alcohol, body

const WINES = [
  {
    id: "w1", name: "Ruffino", style: "sparkling",
    grape: "100% Glera", producer: "Ruffino", region: "Veneto DOC, Italy",
    winemaker: "Ruffino's technical winemaking team",
    flavorTags: ["Green Apple", "Pear", "Citrus", "White Flower"],
    structure: { sweetness: 2, acidity: 4, tannin: 0, alcohol: 2, body: 2 },
    guestDescription: "This is a Prosecco &mdash; light, crisp, a little green apple and pear. Great way to kick off the meal, goes perfect with the oysters.",
    sellingPoints: ["Light and easy to start with", "Built for the raw bar", "Affordable way to go bubbles"],
    winemakingNote: "Made using the Charmat method, where the second fermentation happens in a pressurized tank rather than the bottle &mdash; it keeps the fruit bright and the bubbles softer than Champagne's.",
    moment: "The opening pour, or any guest who wants bubbles without committing to Champagne.",
    memory: "Light, crisp, and the easiest way to start a celebration.",
    pairingDishIds: ["d-oysters", "d-edamame", "d-shishitos"],
    arsenal: "This is the one that makes the first five minutes of the meal feel like a celebration.",
    funFact: "Ruffino has been making wine in Tuscany since 1877 — this Prosecco is a newer addition, since the estate is historically known for Chianti, not sparkling wine.",
    funFact2: "Ruffino is one of the most recognized Italian wine names in the US, largely thanks to their iconic straw-covered Chianti flask from decades past.",
    shortStory: "Ruffino started as a small Tuscan producer in the 1870s and grew into one of Italy's most exported wine names. Their Prosecco line is a newer chapter, built to bring that same reliability to the sparkling category."
  },
  {
    id: "w2", name: "Telmont Réserve Brut", style: "sparkling",
    grape: "Chardonnay, Pinot Meunier, Pinot Noir", producer: "Champagne Telmont", region: "Champagne, France",
    winemaker: "Bertrand Lhôpital, Cellar Master",
    flavorTags: ["Honeysuckle", "Baked Apple", "Brioche", "Chalky Mineral"],
    structure: { sweetness: 1, acidity: 4, tannin: 0, alcohol: 2, body: 3 },
    guestDescription: "This is real Champagne, from a small house in France &mdash; honeysuckle, baked apple, a little brioche. Beautiful with the caviar.",
    sellingPoints: ["Real Champagne, not just sparkling wine", "Rich enough for caviar service", "Backed by a major sustainability push in Champagne"],
    winemakingNote: "Traditional method &mdash; the second fermentation happens right in the bottle, which is what builds the fine, persistent bubbles and the toasty brioche character.",
    moment: "Anniversary dinners, or whenever the table orders the caviar.",
    memory: "Real Champagne pedigree with a toasty, honeyed finish.",
    pairingDishIds: ["d-caviar", "d-shellfish-tower"],
    arsenal: "If they're ordering the caviar, this is the wine that was built for it.",
    funFact: "Telmont is backed by Leonardo DiCaprio, who's an investor and sustainability partner in the house — they're racing to be fully organic by 2031.",
    funFact2: "Telmont was founded in 1912 and is one of the few Champagne houses farming nearly all of its own vineyards with low-intervention, near-organic methods.",
    shortStory: "Founded in a small Marne village in 1912, Telmont stayed under the radar for decades. Recent investment and a sustainability-first mission have turned it into one of Champagne's most talked-about small houses."
  },
  {
    id: "w3", name: "Nicolas Feuillatte Rosé Brut", style: "sparkling",
    grape: "Pinot Noir, Pinot Meunier, Chardonnay", producer: "Champagne Nicolas Feuillatte", region: "Chouilly, Champagne, France",
    winemaker: "Cellar Master & blending team, Centre Vinicole",
    flavorTags: ["Raspberry", "Strawberry", "Red Currant", "Chalk"],
    structure: { sweetness: 1, acidity: 4, tannin: 0, alcohol: 2, body: 3 },
    guestDescription: "This is a ros&eacute; Champagne &mdash; raspberry, strawberry, a little chalky mineral note. Beautiful with the tuna tartare.",
    sellingPoints: ["Prettiest pour on the list", "Pairs with almost anything on the raw bar", "Best-selling Champagne in France"],
    winemakingNote: "Color comes from brief skin contact with Pinot Noir grapes before pressing, plus a small addition of still red wine &mdash; the classic method for ros&eacute; Champagne.",
    moment: "Celebrations, birthdays, or a guest who orders with their eyes first.",
    memory: "A pink Champagne that tastes as good as it looks.",
    pairingDishIds: ["d-tuna-tartare", "d-yellowtail-carpaccio", "d-seared-spicy-salmon-roll"],
    arsenal: "It's the one wine that looks as good as it tastes — a great answer for someone who orders with their eyes first.",
    funFact: "Nicolas Feuillatte is the best-selling Champagne in France — it's a cooperative of over 5,000 growers, not a single royal estate.",
    funFact2: "The house is named after Nicolas Feuillatte, a champagne negociant who founded it in 1976, making it one of the youngest major Champagne names.",
    shortStory: "Built as a cooperative representing thousands of small grower families rather than one aristocratic estate, Nicolas Feuillatte proves Champagne doesn't need centuries of noble history to be excellent — just excellent fruit and blending."
  },
  {
    id: "w4", name: "Santa Margherita", style: "white",
    grape: "100% Pinot Grigio", producer: "Santa Margherita", region: "Alto Adige DOC, Italy",
    winemaker: "Santa Margherita winemaking team",
    flavorTags: ["Green Apple", "Citrus", "White Flowers", "Mineral"],
    structure: { sweetness: 1, acidity: 4, tannin: 0, alcohol: 2, body: 2 },
    guestDescription: "Clean, crisp Pinot Grigio from northern Italy &mdash; green apple, citrus. Simple, reliable, goes with just about anything light.",
    sellingPoints: ["The name everyone already trusts", "Crisp and food-friendly", "Never a wrong answer for the table"],
    winemakingNote: "Fermented and aged in stainless steel with no oak contact, keeping the fruit and acidity front and center.",
    moment: "The guest who just wants 'a nice Pinot Grigio' and isn't looking to explore.",
    memory: "Clean, crisp, and exactly what it promises to be.",
    pairingDishIds: ["d-grilled-romaine", "d-fire-roasted-beets", "d-branzino"],
    arsenal: "It's the wine equivalent of a good handshake — reliable, clean, nobody's ever disappointed.",
    funFact: "Santa Margherita is largely credited with making Pinot Grigio popular in America in the first place.",
    funFact2: "Santa Margherita was founded in 1935 by Count Gaetano Marzotto, named in honor of his late wife, Margherita.",
    shortStory: "Before Santa Margherita, most American drinkers had never heard of Pinot Grigio. Their clean, crisp house style became the template most people now picture when they think of the grape."
  },
  {
    id: "w5", name: "Emmolo", style: "white",
    grape: "100% Sauvignon Blanc", producer: "Emmolo", region: "Napa Valley, California",
    winemaker: "Jenny Wagner",
    flavorTags: ["Citrus Zest", "White Peach", "Fresh Herb", "Wet Stone"],
    structure: { sweetness: 1, acidity: 4, tannin: 0, alcohol: 3, body: 3 },
    guestDescription: "Sauvignon Blanc from the same family as Caymus &mdash; citrus, white peach, fresh herbs. Really bright, great with the raw bar.",
    sellingPoints: ["Same family pedigree as Caymus", "Built for oysters and raw fish", "Bright acidity, zero heaviness"],
    winemakingNote: "Fermented mostly in stainless steel to preserve freshness, with a small portion in neutral oak for texture &mdash; no new oak, so nothing masks the fruit.",
    moment: "Raw bar orders, or a guest who wants a serious white without heaviness.",
    memory: "Crisp, citrusy Sauvignon Blanc with real Napa pedigree.",
    pairingDishIds: ["d-oysters", "d-yellowtail-carpaccio", "d-crunchy-spicy-tuna-roll", "d-131-california-roll"],
    arsenal: "This is the one that makes the raw bar taste like it just came off the boat.",
    funFact: "Emmolo is made by the same family behind Caymus — Emmolo is the maiden name of Charlie Wagner Sr.'s wife.",
    funFact2: "Jenny Wagner is part of the fourth generation of the Wagner family in Napa Valley, and also oversees experimental plantings at the family's Suisun Valley property.",
    shortStory: "Emmolo is Jenny Wagner's own label within the larger Wagner family of wines — named for her mother's side, Sicilian immigrants who ran a grapevine nursery in Napa for decades."
  },
  {
    id: "w6", name: "Cambria 'Katherine's Vineyard'", style: "white",
    grape: "100% Chardonnay", producer: "Cambria", region: "Santa Maria Valley, California",
    winemaker: "Cambria estate winemaking team",
    flavorTags: ["Toasted Oak", "Tropical Fruit", "Baked Apple", "Vanilla"],
    structure: { sweetness: 1, acidity: 2, tannin: 0, alcohol: 4, body: 4 },
    guestDescription: "A rich, buttery Chardonnay &mdash; tropical fruit, toasted oak, a little vanilla. Great with the mac and cheese or the miso cod.",
    sellingPoints: ["Big, rich style for red-wine drinkers", "Pairs with anything buttery", "Reliable Central Coast Chardonnay"],
    winemakingNote: "Barrel-fermented and aged in oak with malolactic conversion, which is what gives it that creamy, buttery texture rather than a crisp, steely one.",
    moment: "Guests who say they don't like white wine but love butter and richness.",
    memory: "A big, buttery Chardonnay that eats like a red.",
    pairingDishIds: ["d-mac-cheese", "d-mashed-potato", "d-miso-cod", "d-wagyu-skirt"],
    arsenal: "Built for anything that comes off the robata with butter on it.",
    funFact: "The vineyard is named for Katherine Jackson, wife of Kendall-Jackson founder Jess Jackson.",
    funFact2: "Cambria was one of several estates founded by Jess and Barbara Banke Jackson as part of building out the Jackson Family Wines portfolio.",
    shortStory: "Katherine's Vineyard sits in the Santa Maria Valley, one of the few California AVAs that runs east-west, funneling cool Pacific air straight through the vines — part of why this Chardonnay keeps its richness without losing freshness."
  },
  {
    id: "w7", name: "Stag's Leap", style: "white",
    grape: "100% Chardonnay", producer: "Stag's Leap Wine Cellars", region: "Napa Valley, California",
    winemaker: "Marcus Notaro, Head Winemaker",
    flavorTags: ["Baked Pear", "Honeysuckle", "Toasted Brioche", "Vanilla Oak"],
    structure: { sweetness: 1, acidity: 3, tannin: 0, alcohol: 4, body: 4 },
    guestDescription: "This is the step-up Chardonnay &mdash; baked pear, honeysuckle, toasted brioche. From the winery that put Napa on the map. Great with the lobster.",
    sellingPoints: ["From the winery that won the Judgment of Paris", "Rich enough to stand up to lobster", "A real occasion bottle"],
    winemakingNote: "Barrel-fermented in French oak with partial malolactic fermentation, balancing richness with enough acidity to stay lifted.",
    moment: "When the dish is the star &mdash; lobster, or a special-occasion table.",
    memory: "Iron fist in a velvet glove &mdash; rich but never heavy.",
    pairingDishIds: ["d-lobster", "d-branzino", "d-chicken-fried-lobster"],
    arsenal: "This is the step-up Chardonnay — order it when the dish is the star and deserves a wine that doesn't hide.",
    funFact: "Stag's Leap Wine Cellars beat top French Bordeaux in the famous 1976 'Judgment of Paris' blind tasting — the event that put Napa on the map.",
    funFact2: "Marcus Notaro joined Stag's Leap Wine Cellars in 2013 after working at Col Solare, and now leads winemaking across the entire estate portfolio.",
    shortStory: "Stag's Leap built its reputation on Cabernet after the 1976 Judgment of Paris, but the estate's Chardonnay carries the same philosophy — richness balanced by restraint, an approach the winery calls 'an iron fist in a velvet glove.'"
  },
  {
    id: "w8", name: "Miraval", style: "white",
    grape: "Grenache, Cinsault, Syrah", producer: "Château Miraval", region: "Côtes de Provence, France",
    winemaker: "Estate winemaking team, Château Miraval",
    flavorTags: ["White Peach", "Citrus", "Floral"],
    structure: { sweetness: 1, acidity: 3, tannin: 0, alcohol: 3, body: 2 },
    guestDescription: "A pale, dry ros&eacute; from Provence &mdash; white peach, citrus, real light and refreshing. Great porch-sipper, easy with the salad.",
    sellingPoints: ["From a famous Provence estate", "Bone dry, not the sweet stuff", "The easiest yes on the list"],
    winemakingNote: "Grapes are pressed gently with minimal skin contact, which is what keeps the color this pale and the style this dry.",
    moment: "Summer patio energy, or a guest who wants something light before the meal.",
    memory: "Pale, dry, and effortlessly easy to drink.",
    pairingDishIds: ["d-chopped-salad", "d-naan", "d-edamame"],
    arsenal: "It drinks like summer in a glass — the easiest 'yes' on the whole list.",
    funFact: "Château Miraval is the property once owned by Brad Pitt and Angelina Jolie — decades earlier, Pink Floyd recorded parts of 'The Wall' in the estate's studio.",
    funFact2: "Miraval has been producing wine since the 16th century, long before its Hollywood ownership — the estate's recording studio has also hosted AC/DC and Sting.",
    shortStory: "Long before it was a celebrity property, Miraval was a working wine estate in the hills of Correns, Provence. Today it's one of the region's most recognized rosé labels, made in a classic pale, dry Provençal style."
  },
  {
    id: "w9", name: "Domaine de la Chezatte Sancerre", style: "white",
    grape: "100% Pinot Noir", producer: "Domaine de la Chézatte", region: "Sancerre, Loire Valley, France",
    winemaker: "Estate winemaking team",
    flavorTags: ["Red Berry", "Citrus", "Flint"],
    structure: { sweetness: 1, acidity: 4, tannin: 0, alcohol: 3, body: 2 },
    guestDescription: "A Sancerre ros&eacute; &mdash; made from Pinot Noir, believe it or not. Red berry, citrus, real minerally. Great with the raw bar or the chowder.",
    sellingPoints: ["Made from Pinot Noir, not a rosé grape", "More mineral, less candy than most rosé", "A conversation starter"],
    winemakingNote: "The Pinot Noir grapes see just a few hours of skin contact before pressing &mdash; barely enough to pick up color, which keeps the wine dry and mineral-driven.",
    moment: "A guest who says they don't usually like ros&eacute;.",
    memory: "Ros&eacute; for people who think they don't like ros&eacute;.",
    pairingDishIds: ["d-clam-chowder", "d-shishitos", "d-hamachi"],
    arsenal: "It's a rosé for people who think they don't like rosé — more mineral, less candy.",
    funFact: "Sancerre rosé is made from Pinot Noir, not a rosé-specific grape — same grape as red Burgundy, just barely kissed by the skins.",
    funFact2: "The estate has been family-run across four generations, farming the same Sancerre limestone hillsides the whole time.",
    shortStory: "Sancerre is famous for white wine, but a small amount of Pinot Noir grown on the same limestone slopes goes into pale, mineral-driven rosé like this one — a style locals drink far more than tourists ever hear about."
  },
  {
    id: "w10", name: "Benton-Lane", style: "red",
    grape: "100% Pinot Noir", producer: "Benton-Lane", region: "Willamette Valley, Oregon",
    winemaker: "Estate winemaking team",
    flavorTags: ["Red Cherry", "Cranberry", "Forest Floor", "Herbal"],
    structure: { sweetness: 1, acidity: 4, tannin: 2, alcohol: 3, body: 2 },
    guestDescription: "A light, bright Pinot Noir from Oregon &mdash; red cherry, cranberry, a little earthy. Drinks almost like a red version of a white wine. Great with the branzino.",
    sellingPoints: ["Red wine that works with fish", "Light-bodied, easy to drink", "Oregon Pinot before it got trendy"],
    winemakingNote: "Estate fruit is dry-farmed, meaning no irrigation &mdash; that stress pushes the vines to root deeper, concentrating flavor in a naturally lighter-bodied wine.",
    moment: "A guest who wants red wine but is ordering fish.",
    memory: "A red that drinks like a white.",
    pairingDishIds: ["d-branzino", "d-miso-cod", "d-chefs-nigiri"],
    arsenal: "This is the red that drinks like a white — perfect if they want red wine but are eating fish.",
    funFact: "The winery's named for the two Oregon counties its vineyard straddles — Benton and Lane.",
    funFact2: "Benton-Lane dry-farms its estate vineyard, meaning the vines get no irrigation — forcing deeper roots and, the winery argues, more concentrated fruit.",
    shortStory: "Founded in the early 1980s in the Willamette Valley, Benton-Lane was one of the earlier wineries to bet on Oregon Pinot Noir before the region became internationally famous for it."
  },
  {
    id: "w11", name: "Flowers", style: "red",
    grape: "100% Pinot Noir", producer: "Flowers Vineyard & Winery", region: "Sonoma Coast, California",
    winemaker: "Chantal Forthun, Director of Winemaking",
    flavorTags: ["Wild Strawberry", "Dark Cherry", "Baking Spice", "Earthy Mineral"],
    structure: { sweetness: 1, acidity: 3, tannin: 2, alcohol: 3, body: 3 },
    guestDescription: "Pinot Noir from the wildest part of the Sonoma Coast &mdash; wild strawberry, dark cherry, real earthy. Structured enough to handle the skirt steak.",
    sellingPoints: ["Grown on the most extreme coastline in Sonoma", "Elegant but has real backbone", "Stands up to steak, unlike most Pinot"],
    winemakingNote: "Uses native yeast fermentation and minimal intervention, letting the cool, foggy vineyard site speak for itself rather than winemaking technique.",
    moment: "A Pinot lover who wants something with real structure, or pairing with the skirt steak.",
    memory: "The Pinot that can actually handle a steak.",
    pairingDishIds: ["d-wagyu-skirt", "d-short-rib", "d-negi-toro-roll", "d-marinated-chicken"],
    arsenal: "This is the Pinot for people who think Pinot can't stand up to a steak — this one can.",
    funFact: "Flowers' vineyards sit on an exposed, foggy Sonoma Coast ridge so remote that most winemakers thought it was too extreme to grow anything.",
    funFact2: "Chantal Forthun has led winemaking at Flowers since 2012, working from vineyards remote enough that the team can sometimes hear sea lions barking on the coastal breeze.",
    shortStory: "Founded by Walt and Joan Flowers in 1989 on land most winemakers considered too extreme to farm, Flowers helped prove the far Sonoma Coast could produce some of California's most elegant Pinot Noir."
  },
  {
    id: "w12", name: "Corazon del Sol", style: "red",
    grape: "100% Malbec", producer: "Corazón del Sol", region: "Uco Valley, Mendoza, Argentina",
    winemaker: "Estate winemaking team, Uco Valley",
    flavorTags: ["Black Plum", "Blackberry", "Violet", "Tar & Spice"],
    structure: { sweetness: 1, acidity: 3, tannin: 3, alcohol: 4, body: 4 },
    guestDescription: "A Malbec from high up in the Andes &mdash; black plum, blackberry, a little violet. Rich but the tannins are soft. Great with the short rib.",
    sellingPoints: ["Classic Argentine Malbec", "High-altitude fruit, riper and softer", "A crowd-pleaser for red drinkers"],
    winemakingNote: "Fruit is grown over 3,600 feet up, where intense sunlight and cool nights build deep color and ripe tannin without losing acidity.",
    moment: "A guest who wants a big, easy red without sharp edges.",
    memory: "Rich, ripe Malbec from way up in the mountains.",
    pairingDishIds: ["d-short-rib", "d-marinated-chicken", "d-burger"],
    arsenal: "High-altitude Malbec — the fruit is riper and the tannins softer than what people expect.",
    funFact: "The vineyards sit over 3,600 feet up in the Andes foothills — that altitude is what gives the wine its brighter acidity.",
    funFact2: "Corazón del Sol translates to 'heart of the sun,' a nod to the intense high-altitude sunlight the Uco Valley gets year-round.",
    shortStory: "Malbec followed French immigrants to Argentina in the 1800s and nearly disappeared after a hard frost in the 1950s. High-altitude sites like this one in the Uco Valley are part of why the grape came roaring back as Argentina's signature red."
  },
  {
    id: "w13", name: "Markham", style: "red",
    grape: "Merlot-dominant blend", producer: "Markham Vineyards", region: "Napa Valley, California",
    winemaker: "Estate winemaking team",
    flavorTags: ["Black Cherry", "Plum", "Cocoa", "Baking Spice"],
    structure: { sweetness: 1, acidity: 3, tannin: 2, alcohol: 4, body: 3 },
    guestDescription: "A soft, approachable Merlot &mdash; black cherry, plum, a little cocoa. No hard edges at all. Great for someone who says they don't like big reds.",
    sellingPoints: ["The easiest red on the list", "Full flavor, no harsh tannin", "One of Napa's older properties"],
    winemakingNote: "Aged in a mix of French and American oak with gentle extraction during fermentation, keeping the tannins soft rather than gripping.",
    moment: "The guest who says 'I don't do big reds.'",
    memory: "Full-flavored red with absolutely no bite.",
    pairingDishIds: ["d-marinated-chicken", "d-short-rib"],
    arsenal: "This is the wine for the guest who says 'I don't do big reds' — full flavor, none of the grip.",
    funFact: "Markham is one of Napa's older wineries, dating to the 1870s — the stone building on the property is original.",
    funFact2: "Markham was one of the first Napa wineries to release a varietal Merlot as its own standalone wine, back when most Merlot was only used for blending.",
    shortStory: "The winery's stone building dates to the 1870s, making Markham one of the physically oldest working wine properties in Napa Valley, even though the Markham name itself came later."
  },
  {
    id: "w14", name: "Austin Hope", style: "red",
    grape: "Cabernet Sauvignon", producer: "Austin Hope", region: "Paso Robles, California",
    winemaker: "Austin Hope",
    flavorTags: ["Blackberry", "Dark Chocolate", "Vanilla Oak", "Warm Spice"],
    structure: { sweetness: 1, acidity: 2, tannin: 4, alcohol: 5, body: 4 },
    guestDescription: "A big, ripe Cabernet from Paso Robles &mdash; blackberry, dark chocolate, warm spice. Rounder than a Napa Cab. Great with the ribeye.",
    sellingPoints: ["Riper, rounder style than Napa Cab", "Built for a big steak", "Named after the winemaker himself"],
    winemakingNote: "Aged extensively in new French oak, which is where a lot of that dark chocolate and vanilla character comes from rather than the fruit alone.",
    moment: "A guest who wants power without sharp tannin &mdash; order it with the ribeye.",
    memory: "Big, ripe Cabernet built for a big cut of steak.",
    pairingDishIds: ["d-ribeye", "d-ny-strip-14", "d-short-rib", "d-bone-marrow"],
    arsenal: "Paso Cab runs riper and rounder than Napa — order it for the guest who wants power without sharp edges.",
    funFact: "Austin Hope is named after the winemaker himself — his family were early pioneers who helped put Paso Robles on the map as a serious Cabernet region.",
    funFact2: "Austin Hope's father, Chuck Hope, was one of the first to plant Cabernet Sauvignon on Paso Robles' west side, helping establish the region as serious Cabernet country.",
    shortStory: "Built on ripe, generous Paso Robles Cabernet at a time when most collectors only took Napa seriously, Austin Hope's namesake wine helped change that conversation."
  },
  {
    id: "w15", name: "Oberon", style: "red",
    grape: "Cabernet Sauvignon", producer: "Oberon", region: "Napa Valley, California",
    winemaker: "Chuck Wagner",
    flavorTags: ["Dark Berry", "Cassis", "Oak Spice", "Mocha"],
    structure: { sweetness: 1, acidity: 3, tannin: 3, alcohol: 4, body: 3 },
    guestDescription: "Same family as Caymus &mdash; dark berry, cassis, a little mocha. Real smooth. Goes great with the filet.",
    sellingPoints: ["Same family pedigree as Caymus", "Smooth and approachable", "A friendlier price than the big name"],
    winemakingNote: "Aged in a mix of French and American oak with a moderate new-oak percentage &mdash; enough to round the tannin without covering up the fruit.",
    moment: "A weeknight steak dinner, or a first-time Napa Cab guest.",
    memory: "Easy, approachable Napa Cabernet with real pedigree behind it.",
    pairingDishIds: ["d-filet-8", "d-bone-in-filet", "d-burger"],
    arsenal: "Same family as Caymus, built to drink younger and lighter on the wallet — great everyday steak Cab.",
    funFact: "Oberon is named after the King of the Fairies from Shakespeare's 'A Midsummer Night's Dream.'",
    funFact2: "Oberon is made by the same Wagner family and winemaking team behind Caymus, built as a more approachable, earlier-drinking Cabernet at a lower price point.",
    shortStory: "Named after Shakespeare's fairy king, Oberon was built to be Caymus's more playful, easy-drinking little sibling — same winemaking hand, lighter price tag."
  },
  {
    id: "w16", name: "Caymus", style: "red",
    grape: "Cabernet Sauvignon", producer: "Caymus Vineyards", region: "California",
    winemaker: "Chuck Wagner",
    flavorTags: ["Black Currant", "Mocha", "Vanilla", "Toasted Oak"],
    structure: { sweetness: 1, acidity: 2, tannin: 3, alcohol: 5, body: 5 },
    guestDescription: "This is Caymus &mdash; rich black currant, mocha, vanilla. Big, plush, the name everyone already knows. Perfect with the tomahawk.",
    sellingPoints: ["The name guests already ask for", "Rich enough for the biggest cuts", "Two-time Wine Spectator Wine of the Year producer"],
    winemakingNote: "Aged in a high percentage of new French and American oak for an extended period, building the deep vanilla and mocha character the label is known for.",
    moment: "Any big-format steak &mdash; tomahawk, porterhouse &mdash; or a guest who already knows the name.",
    memory: "The Cabernet everyone already trusts.",
    pairingDishIds: ["d-tomahawk", "d-porterhouse", "d-ny-strip-16", "d-bone-marrow"],
    arsenal: "This is the name guests ask for by default — lean into it, it sells itself.",
    funFact: "Caymus takes its name from 'Rancho Caymus,' the original Spanish land grant covering part of Napa Valley — founded by Charlie Wagner Sr. in 1972, still family-run today.",
    funFact2: "Chuck Wagner was only 19 when he started Caymus with his parents in 1972 — the winery is still entirely family-run over 50 years later, with his own children Charlie and Jenny now involved.",
    shortStory: "Caymus's 1984 and 1990 Special Selection Cabernets were both named Wine Spectator's 'Wine of the Year' — the only producer ever to win that honor twice — cementing Caymus as one of the most recognized Cabernet names in the world."
  },
  {
    id: "w17", name: "Domaine de Cabasse 'Cuvée Marguerite'", style: "red",
    grape: "Grenache, Syrah", producer: "Domaine de Cabasse", region: "Côtes-du-Rhône, France",
    winemaker: "Estate winemaking team",
    flavorTags: ["Cranberry", "Wild Strawberry", "Garrigue Herbs", "Pepper"],
    structure: { sweetness: 1, acidity: 3, tannin: 2, alcohol: 4, body: 3 },
    guestDescription: "A Southern Rh&ocirc;ne blend &mdash; cranberry, wild strawberry, herby. Tastes like the south of France. Great with the naan or the chicken.",
    sellingPoints: ["Tastes like Provence in a glass", "Food-friendly, not heavy", "A change of pace from the usual reds"],
    winemakingNote: "Grenache and Syrah are blended after fermentation, with the Grenache giving juicy fruit and the Syrah adding structure and pepper.",
    moment: "A guest who wants something different from the usual Cab or Merlot.",
    memory: "Herby, sun-warmed red that tastes like southern France.",
    pairingDishIds: ["d-naan", "d-marinated-chicken", "d-wild-mushrooms"],
    arsenal: "It's the wine that tastes like the south of France smells — herby, sun-warmed, easy to fall for.",
    funFact: "The estate's roots trace back to the 14th century, when the Popes lived in nearby Avignon.",
    funFact2: "The estate grows its Grenache and Syrah on rocky, sun-baked hillsides typical of the southern Rhône, where the region's fierce Mistral wind helps keep the vines naturally healthy.",
    shortStory: "'Cabasse' is believed to come from an old term for 'the house below the village,' referring to its position just beneath the hilltop town — a name that's stuck since the days the Popes lived down the road in Avignon."
  },
  {
    id: "w18", name: "Madame de Beaucaillou", style: "red",
    grape: "Merlot, Cabernet Sauvignon, Petit Verdot, Cabernet Franc", producer: "Château Ducru-Beaucaillou", region: "Haut-Médoc, Bordeaux, France",
    winemaker: "Winemaking team, Château Ducru-Beaucaillou",
    flavorTags: ["Blackcurrant", "Violet", "Morello Cherry", "Oak Spice"],
    structure: { sweetness: 1, acidity: 3, tannin: 3, alcohol: 3, body: 4 },
    guestDescription: "This is a real Bordeaux ch&acirc;teau pour, just the second label &mdash; blackcurrant, violet, a little cherry. Elegant, not heavy. Great with the short rib.",
    sellingPoints: ["Real classified-Bordeaux pedigree", "Elegant, refined tannin", "A special bottle at a by-the-glass price"],
    winemakingNote: "Blended from younger vines and lots declassified from the estate's flagship wine, aged in French oak in the same cellar as the grand vin.",
    moment: "A guest who wants to say they had real Bordeaux tonight.",
    memory: "Real ch&acirc;teau Bordeaux, without the ch&acirc;teau price tag.",
    pairingDishIds: ["d-short-rib", "d-bone-in-filet"],
    arsenal: "This is a real Bordeaux château pedigree at a by-the-glass price — worth saying that part out loud.",
    funFact: "'Madame' is the second wine of a famous St-Julien château — made from younger vines and declassified lots from a much more expensive estate wine.",
    funFact2: "Château Ducru-Beaucaillou is a classified Second Growth (Deuxième Cru) in the famous 1855 Bordeaux Classification, one of the most prestigious rankings in all of wine.",
    shortStory: "'Madame' gives guests a taste of real, classified Bordeaux château pedigree — made from younger vines and lots that don't quite make the cut for the flagship wine — without the flagship price tag."
  },
  {
    id: "w19", name: "Trefethen 'Eshcol'", style: "red",
    grape: "Cabernet Sauvignon-led Bordeaux blend", producer: "Trefethen Family Vineyards", region: "Oak Knoll District, Napa Valley, California",
    winemaker: "Estate winemaking team",
    flavorTags: ["Black Cherry", "Dried Herb", "Cedar", "Baking Spice"],
    structure: { sweetness: 1, acidity: 3, tannin: 3, alcohol: 4, body: 3 },
    guestDescription: "A Bordeaux-style blend from Napa &mdash; black cherry, cedar, dried herb. More complexity than a straight Cab. Great with the tenderloin.",
    sellingPoints: ["A blend, more layers than a single grape", "Same price as a straight Cab, more complexity", "From one of Napa's oldest wooden wineries"],
    winemakingNote: "Blended from multiple Bordeaux varieties aged separately in French oak before final blending, which builds layered complexity a single varietal can't achieve alone.",
    moment: "A guest who wants something more interesting than a straight Cabernet.",
    memory: "More complexity in the glass than a straight Cab at the same price.",
    pairingDishIds: ["d-tenderloin-8", "d-wagyu-skirt", "d-short-rib"],
    arsenal: "It's a blend, not a single grape — more complexity in the glass than a straight Cab at the same price.",
    funFact: "'Eshcol' is a biblical name for a valley famous for its grapes — also the name of the historic wooden winery building on Trefethen's property, built in 1886.",
    funFact2: "Trefethen is one of the few wineries in Napa Valley within the cooler Oak Knoll District, which sits at the valley's southern end and gets more fog influence than areas further north.",
    shortStory: "The winery's original wooden building, called Eshcol, was built in 1886 and is one of the oldest wooden wine structures still in use in Napa Valley — the wine takes its name directly from it."
  },
  {
    id: "w20", name: "Yoshi No Gawa 'Winter Warrior'", style: "sake",
    grape: "Gohyakumangoku rice, 60% polish", producer: "Yoshinogawa", region: "Niigata Prefecture, Japan",
    winemaker: "Toji (master brewer), Yoshinogawa Brewery",
    flavorTags: ["Melon", "Honeydew", "Lychee", "Floral"],
    structure: { sweetness: 2, acidity: 1, tannin: 0, alcohol: 3, body: 3 },
    guestDescription: "A junmai ginjo sake from Niigata &mdash; melon, honeydew, a little lychee. Clean and light. Perfect if you're doing the sushi or the omakase.",
    sellingPoints: ["Built specifically for raw fish", "Clean, light, refreshing", "Brewed by a house going on 500 years"],
    winemakingNote: "Milled to 60% of the original rice grain size before brewing &mdash; the more the rice is polished, the cleaner and more fragrant the sake becomes.",
    moment: "Any table doing sushi, sashimi, or the omakase.",
    memory: "The pour that actually matches the fish instead of fighting it.",
    pairingDishIds: ["d-sushi-sashimi-nigiri", "d-sushi-rolls", "d-sashimi-platter", "d-omakase-platter", "d-ikura", "d-tamagoyaki", "d-unagi"],
    arsenal: "For a table doing the omakase or the platter, this is the pour that actually matches the fish instead of fighting it.",
    funFact: "Yoshinogawa was founded in 1548 — it's the oldest sake brewery in Niigata Prefecture and the eighth oldest in all of Japan.",
    funFact2: "Niigata is famous for heavy winter snowfall, which filters into extremely pure water used in brewing — part of why the region is known for clean, crisp sake styles.",
    shortStory: "Yoshinogawa has been brewing sake in the same Niigata region since 1548 — meaning this bottle carries nearly 500 years of continuous brewing tradition behind it."
  }
];

const DISHES = [
  { id: "d-oysters", name: "East Coast Oysters", section: "Raw Bar", description: "Chilled: fresh wasabi, shallots, ponzu. Roasted: coconut, chili, cilantro, lime.", pairedWineIds: ["w1", "w5"], quizClue: "Served two ways: raw on the half shell with shallot ponzu and fresh wasabi, or shocked and finished with a charred fresno-coconut vinaigrette and toasted panko.", dropLine: "eastern oysters with shallot ponzu and fresh wasabi / roasted oysters with charred fresno and coconut vinaigrette", ingredients: "house made shallot ponzu - gluten free soy sauce, mirin, rice vinegar, sake, konbu, bonito flakes, minced shallots, orange peel and orange juice. | charred fresno and coconut vinaigrette- red bell pepper, shiro dashi (bonito flakes, konbu, soy sauce, mirin, sake, salt, sugar), fresno pepper, fish sauce, rice vinegar, coconu milk, lime juice, lime zest, sugar", chefPrep: "6 each freshly shucked eastern oyster served with housemade shallot ponzu sauce, fresh grated wasabi root and lemon wedge | for charred fresno vinaigrette all ingredients blended well until smooth and strained. For oysters shocked fresh and dresed with charred fresno vin, toasted panko and roasted in the oven until done. Plated with plating salt underneath and garnished with lemon wedge", allergensInRecipe: ["alcohol", "fish", "soy", "vinegar", "citrus", "chili", "shellfish", "onion"], allergensRemovable: ["onion", "mustard"] },
  { id: "d-tuna-tartare", name: "Tuna Tartare", section: "Raw Bar", description: "Avocado purée, wakamomo, chives, taro chips, sesame garlic soy dressing", pairedWineIds: ["w3"], quizClue: "Diced yellowfin mixed with olive oil and chives, built in a ring mold over a piped avocado-yuzu puree.", dropLine: "yellowfin tuna tartar with avocado puree and taro chips", ingredients: "tartar build- diced yellowfin tuna, chives, avocado puree, yuzu garlic soy dressing,  olive oil.  avocado puree- yuzu juice, evoo, olive oil, black pepper, avocado. Sesame garlic soy dressing- garlic, mirin, sesame oil, soy sauce, yuzu juice, rice vinegar. Garnish- taro chips, wakamomo(young peach in syrup), radish", chefPrep: "finely diced yellowfin tuna mixed with olive oil, chives, salt and pepper. Then ring mold placed on the bowl and avocado puree piped nicely. Follow by tuna mix. Garnished with julienne red radish, wakamomo, sesame garlic soy dressing. Served with taro chips on the side. if guest has glutten Allergy sub for Ponzu Sauce", allergensInRecipe: ["fish", "soy", "sesame", "garlic", "alcohol", "vinegar", "citrus", "onion", "gluten"], allergensRemovable: ["onion", "garlic", "gluten", "sesame"] },
  { id: "d-yellowtail-carpaccio", name: "Yellowtail Carpaccio", section: "Raw Bar", description: "Orange supreme, shishito, wakamomo citrus ponzu, ichimi togarashi", pairedWineIds: ["w3", "w5"], quizClue: "Five thin slices of hamachi dressed in a sweet-tart ponzu made with baby Japanese peach, orange segments, and togarashi.", dropLine: "yellowtail carpaccio with cripsy rice, Wakamomo Ponzu", ingredients: "Wakamomo Ponzu Sauce- House ponzu, orange juice, togarashi shimi, sesame oil, chanpagne vinegar, baby japanese peach, sugar, glucose syrup", chefPrep: "One cold plate, 5 slices Hamachi, orange segments, sliced shitshitos,Wakamomo Ponzu, Ichimi Togarashi, cracker arare, micro cilantro", allergensInRecipe: ["fish", "sesame", "vinegar", "citrus", "chili", "alcohol", "soy"], allergensRemovable: ["chili"] },
  { id: "d-caviar", name: "Prime 131 Reserve Caviar", section: "Raw Bar", description: "House reserve caviar service", pairedWineIds: ["w2"], quizClue: "Royal white sturgeon roe, farmed for large jet-black pearls with a creamy, buttery pop, served with blinis and a mascarpone dressing.", dropLine: "(choice of caviar) with traditional accoutrements", ingredients: "choice of caviar- mini blinis, shallots, egg yolk, egg white, mascarpone dressing, chives", chefPrep: "Royal White sturgeon Caviar. Farmed large pearls  jet black color with a creamy buttery flavor and smooth pop", allergensInRecipe: ["dairy", "eggs", "fish", "gluten", "onion"], allergensRemovable: ["dairy", "eggs", "gluten", "onion"] },
  { id: "d-shellfish-tower", name: "Fire Grilled Shellfish Tower", section: "Raw Bar", description: "1lb stone crab, 6 prawns, 12 roasted oysters, whole roasted lobster", pairedWineIds: ["w2"], quizClue: "A whole Maine lobster, a stone crab claw, a dozen oysters, and six head-on shrimp, all cooked hot over an open flame and stacked together for the table.", dropLine: "Prime 131 grilled shellfish tower", ingredients: "grilled shellfish tower- 1.5 lbs whole maine lobster, 1 lb Stone Crab Claw, 12 pcs roasted oysters, 6 each grilled head on shrimp. Garnish- lemon wedge.", chefPrep: "oysters are not gluten free but can be gluten free. Losbter, king crab, oyster and shrimp all grilled and served hot. We recommed guest enjoy the dish right away to avoid butter get solidified.", allergensInRecipe: ["shellfish", "dairy", "citrus", "gluten"], allergensRemovable: ["citrus", "gluten"] },

  { id: "d-sourdough", name: "Grilled Sourdough Bread", section: "Starters", description: "Beurre d'Isigny, Maldon salt", pairedWineIds: [], quizClue: "Sliced and brushed with olive oil, cooked crisp on the outside and fluffy within over the wood fire, served with French cultured butter and Maldon salt.", dropLine: "grilled local sourdough bread with beurre d'Isigny", ingredients: "sourdough bread - beurre d'Isigny cows milk butter from France, olive oil, Maldon sea salt", chefPrep: "sliced sourdough bread brushed with olive oil and grilled on the wood fire grill until crispy outside and fluffy inside. Served with butter and salt on the side", allergensInRecipe: ["gluten", "dairy"], allergensRemovable: ["dairy"] },
  { id: "d-naan", name: "Grilled Naan", section: "Starters", description: "Choice of baba ganoush, labneh, or whipped ricotta", pairedWineIds: ["w8", "w17"], quizClue: "A warm flatbread served with a trio of dips: smoky charred-eggplant baba ganoush, tangy garlic-lemon labneh, and whipped ricotta.", dropLine: "grilled pita with, babaganoush, lebaneh, whipped ricotta", ingredients: "Babaganoush base- eggplant, tahini (ground sesame paste) lemon juice, garlic, cumin, Garnish- sumac, parsley, capers, olive oil. Lebaneh- garlic, lemon juice, olive oil, Garnish- sheeps milk feta zatar, parsley, moroccan dry cured olives, olive oil. Whipped ricotta - heavy cream. Garnish-  honey, chives, olive oil, grilled pita bread", chefPrep: "babaganoush- eggplant charred over open flame and all meat separated from skin, chopped and cooled. Next day mixed with tahini, lemon juice, garlic, cumin and kept cold for service. Lebaneh- high quality lebaneh mixed well with garlic, lemon juice and olive oil. and keept cold for service. Whipped ricotta- whipped with heacy cream to achieve fluffy consistency and kept cold service. Trio of dips offered together with grilled fresh pita bread", allergensInRecipe: ["sesame", "citrus", "garlic", "gluten", "dairy", "onion"], allergensRemovable: ["gluten", "onion"] },
  { id: "d-shishitos", name: "Fried Shishitos", section: "Starters", description: "Ponzu, sesame seeds", pairedWineIds: ["w1", "w9"], quizClue: "Japanese blistering peppers, quick-cooked until the skin lightly chars, then tossed with furikake seasoning and house ponzu.", dropLine: "fried shishitos with furikake and ponzu", ingredients: "shishitos- house made ponzu, salt, black pepper,  toasted sesame seeds and Furikake seasoning. House made Ponzu- gluten free soy sauce, mirin, rice vinegar, sake, konbu, bonito flakes, orange peel and orange juice. Served Ponzu Emulsion", chefPrep: "japanese shishito peppers fried until skin is slightly cooked. Then transferred to bowl and seasoned with furikake seasoning and ponzu sauce. Plated in a small plate and garnished with sesame seeds. Gluten free", allergensInRecipe: ["fish", "alcohol", "vinegar", "citrus", "sesame", "soy"], allergensRemovable: [] },
  { id: "d-chicken-fried-lobster", name: "Chicken Fried Lobster", section: "Starters", description: "Brown butter aioli, preserved lemon gel, micro greens", pairedWineIds: ["w7"], quizClue: "Live tail meat, poached then double-breaded in a gluten-free coating and cooked to a deep golden crust, served with a brown butter aioli.", dropLine: "chicken fried lobster with preserved lemon gel and brown butter aioli", ingredients: "brown butter aioli- dijon mustard, egg, salt, brown butter, garlic confit. Breading for lobster- gluten free flour, rice flour, corn starch, xantan gum, baking powder, egg, half & half. Preserved lemon gel- lemon, water, sugar, agar agar, mayer lemons, salt, black peppercorn, coriander, bay leaf, star anise, cinnamon.", chefPrep: "for brown butter all ingredients blended together while slowly adding brown butter until fully imulsifies. Breading for lobster- live maine lobster poached for 30 seconds to take out of the meat from shell. Then cut into medallions. Then egg and half and half mixed well and set a side. in other bowl all dry ingredients mixed. lobster medallions breaded with dry mix, egg wash and back to dry mix. and set a side for service. for preserved lemon gell- lemons are scored and cured with al ingredients for 15-30 days. then washed well skin is separated for a gell. then skin is boiled  with all ingredients and blended until smooth after cooled dowm. during pick up medallions fried until golden brown and ganished with preserved lemon gel, micro greens, lemon gel and brown butter aioli on the side", allergensInRecipe: ["mustard", "eggs", "dairy", "garlic", "citrus", "shellfish"], allergensRemovable: ["citrus", "garlic", "mustard"] },
  { id: "d-bone-marrow", name: "Dinosaur Bone Marrow", section: "Starters", description: "Onion jam, braised short ribs, grilled sourdough", pairedWineIds: ["w14", "w16"], quizClue: "A roasted beef center-cut, split and served with a fermented black garlic sauce and a sweet onion jam.", dropLine: "grilled dinosaur bone marrow with braised short rib and onion jam", ingredients: "fermented garlic sauce- onion, garlic, pasilla chili powder, cumin, coriander, bay leaf, sherry vinegar, sugar, salt, black pepper, black garlic, olive oil. Shallot jam- oil, onion, sugar, brown sugar, water, salt, black pepper. Braised shredded short rib- same as short rib entree", chefPrep: "for fermented black garlic sauce, onions grilled nicely until charred. Then all ingredients blended together until smooth and seasoned nicely. For shllots jam- all ingredients cooked until soft and blended until smooth. Bone marrow is brined with salt and water overnight to take out all blood from them. during service it cooked in the hot oven. same time short rib is heat up with black garlic sauce and plated on the bonemarrow once it ready. garnished with sliced serrano, onion jam, puffed sorghum, Maldon salt, chervil,, grilled sourdough", allergensInRecipe: ["chili", "garlic", "onion", "vinegar", "gluten", "dairy", "alcohol"], allergensRemovable: ["gluten", "dairy"] },
  { id: "d-crab-cakes", name: "Jumbo Lump Mini Crab Cakes", section: "Starters", description: "Spicy aioli, frisée, honey-lime vinaigrette", pairedWineIds: [], quizClue: "Maryland-style seafood fritters bound with mayo, old bay, and panko, fried golden and served over a lime-honey friseé salad.", dropLine: "jumbo lump maryland mini crab cakes with", ingredients: "Crab cake mix- maryland crab, mayo, old bay, lemon juice and zest, egg, panko, chives. frisee salad- lime honey dressing, chives. Lime honey dressing - lime juice, honey, salt, blended oil. Spicy  mayo - mayo, schimi togarashi (japanese 7 spice), sesame oil, chili oil, ponzu, yuzu juice, salt.", chefPrep: "5 each (4 oz total) crab fritters fried until golden brown and plated with spicy mayo and frisee salad.", allergensInRecipe: ["shellfish", "eggs", "citrus", "gluten", "onion", "chili", "sesame", "soy"], allergensRemovable: [] },
  { id: "d-edamame", name: "Edamame", section: "Starters", description: "Choice of sea salt, lemon, or spiced", pairedWineIds: ["w1", "w8"], quizClue: "Steamed Japanese soybeans finished with Maldon salt and lemon, or sauteed in a chili-garlic sauce as a spicier option.", dropLine: "steamed edamame with maldon sea salt and lemon or fried edamame with chili garlic sauce", ingredients: "edamame (soy beans)- Maldon sea salt and lemon. Chili garlic sauce- chili pepper, salt, sugar, water, rice vinegar, garlic, corn starch, sesame oil, pickled ginger juice, soy sauce, mushroom extract.", chefPrep: "Japanese soy beans steam until hot and seasoned with Maldon sea salt and garnished with lemon wedge. Gluten free. 2nd option  steamed soy beans sautéed with sesame oil and chili garlic sauce. Not gluten free", allergensInRecipe: ["citrus"], allergensRemovable: ["soy", "gluten", "sesame", "garlic", "vinegar", "chili"] },

  { id: "d-clam-chowder", name: "Smoked Clam Chowder", section: "Soups & Salads", description: "Bacon bits, crispy potato, celery leaves, chili oil", pairedWineIds: ["w9"], quizClue: "A cream-based bivalve soup built on leeks, celery, and cured pork hock, finished with a touch of chili oil.", dropLine: "smoked clam chowder with crispy potato and bacon", ingredients: "clam chowder base- leeks, celery, onion, garlic, ap flour, white wine, bay leaf, aleppo pepper, olive oil, butter, smoked pork hocks, heavy cream, clams, salt, clam juice. Garnish- chili oil, crispy potatoes, celery leaves, bacon bits", chefPrep: "all vegetables cooked with olive oil until soft. Then butter added follow by sifted flour. Once flour  is fully cooked heavy cream, clam juice, pork hock, bay leaf and aleppo pepper. Seasoned with salt at the end and ready to serve. Garnished with chili oil, crispy potato, celery leaves and bacon. Do not split the soup when taking order from guest", allergensInRecipe: ["onion", "garlic", "gluten", "alcohol", "dairy", "shellfish", "pork", "chili"], allergensRemovable: ["chili"] },
  { id: "d-grilled-romaine", name: "Grilled Romaine Salad", section: "Soups & Salads", description: "Lemon candy, parmesan breadcrumbs, anchovy black garlic sauce", pairedWineIds: ["w4"], quizClue: "Charred lettuce halved and topped with anchovies, a black garlic caesar dressing, and herb breadcrumbs.", dropLine: "grilled romaine with black garlic dressing and anchovies", ingredients: "Herb de province bread crumbs- sourdough bread,thyme, basil, rosemary, tarragon, marjoram, oregano, bay leaf. Black garlic caesar dressing- garlic, anchovies, dijon mustard, eggs, lemon zest, black garlic, canola oil, white vinegar, salt, pepper, parmesan cheese. candied lemon peel- water, sugar, lemon peel.", chefPrep: "romaine lettuce  split in half, grilled and placed on the place. Garnished with anchovies, herb de province bread crumbs, black garlic caesar dressing, candied lemon peel, parmesan cheese, chervil and fresh lemon juice", allergensInRecipe: ["gluten", "garlic", "fish", "mustard", "eggs", "citrus", "vinegar", "dairy"], allergensRemovable: ["gluten"] },
  { id: "d-chopped-salad", name: "Prime 131 Chopped Salad", section: "Soups & Salads", description: "House mixed baby greens, shaved red onion, cherry tomato, feta, shaved radish, plum vinaigrette", pairedWineIds: ["w8"], quizClue: "A mix of greens, romaine, and friseé tossed with cherry tomatoes, watermelon radish, feta, and a creamy plum vinaigrette.", dropLine: "House Salad", ingredients: "Creamy Plum Vin. olive oil, Wakamomo, Apple cider vinegar, Plum Syrup, Champange Vinegar, dijon, mayo, honey.", chefPrep: "Mix Green MIx, Romaine, Frissee, Cherry Tomatoes, Red onion, watermelon radish,cucumber, Feta Cheese", allergensInRecipe: ["vinegar", "mustard", "eggs", "onion", "dairy"], allergensRemovable: ["onion", "dairy"] },
  { id: "d-fire-roasted-beets", name: "Fire-Roasted Beets", section: "Soups & Salads", description: "Labneh, pistachio dukkah, scallions", pairedWineIds: ["w4"], quizClue: "Gold and red root vegetables cooked whole over an open flame, marinated, and topped with a pistachio dukkah and tangy labneh.", dropLine: "fire roasted beets with lebaneh and pistachio dukka", ingredients: "beet marinade- red wine vinegar, honey, sugar, salt, black pepper, thyme, shallots. Pistachio dukka- pistachios, toasted white sesame seeds, salt, pepper, cumin, coriander. Lebaneh- same and dip recipe", chefPrep: "gold and red beets roasted on wood fire until soft. Then cooled down and peeled. Cut into bite size pcs and marinated right before service. During pickup lebaneh spread on the botto, of the plate. Follow by marinated beet, pistachio dukka and scallions.", allergensInRecipe: ["vinegar", "onion", "nuts", "sesame", "dairy", "garlic"], allergensRemovable: [] },

  { id: "d-lobster", name: "Whole Roasted Lobster", section: "Entrées", description: "Grilled lemon, garlic ponzu butter", pairedWineIds: ["w7"], quizClue: "A live Maine catch, poached and cooled to separate the meat, then rewarmed in a garlic-ponzu butter with togarashi and shiso.", dropLine: "Whole roasted lobster 1.5# with garlic ponzu butter", ingredients: "Garlic ponzu butter - jalapenos, garlic, togarashi (japanese 7 spice) salt, shiso leaves (japanese mint), house ponzu.", chefPrep: "Live maine lobsters 1.5lbs lightly poachaed and cooled in ice water to separate meat from the shell. Then diced into bite size pcs and put back into shell. During service topped with garlic ponzu butter and roasted in the high heat oven until medium well. Served with grilled lemon", allergensInRecipe: ["shellfish", "garlic", "chili", "soy", "alcohol", "dairy", "citrus"], allergensRemovable: ["citrus"] },
  { id: "d-miso-cod", name: "Miso Marinated Cod", section: "Entrées", description: "Grilled bok choy, coconut lemongrass espuma", pairedWineIds: ["w6", "w10"], quizClue: "Alaskan wild sablefish, cured for 24 hours in a fermented soybean paste, finished with a coconut-lemongrass espuma.", dropLine: "miso marinated black cod with grilled bok choy and coconut lemongrass espuma", ingredients: "coconut lemongrass espuma- coconut milk, lime juice and zest, kaffir lime leaf, ginger, lemongrass, cilantro, bay leaf, thai chili, basil, mint, agar agar. Gluten free miso marinade- sake, mirin, sugar, white miso.  For regular black cod marinade- all ingredients above plus soy sauce, garlic, ginger, corn starch. Garnish- dried chive powder.", chefPrep: "Alaskan wild balck cod portioned into 8 oz pcs and marinated in miso marinade for at least 24 hours. Then during service it cooked in the jasper until caramelized and bones taken out and served with no skin. Bok choy blanched before service", allergensInRecipe: ["fish", "alcohol", "chili", "citrus", "soy", "garlic", "gluten"], allergensRemovable: ["chili", "citrus", "garlic", "gluten"] },
  { id: "d-burger", name: "Prime 131 Burger", section: "Entrées", description: "American cheese, veal bacon, brioche bun, special sauce, french fries", pairedWineIds: ["w12", "w15"], quizClue: "A grilled house-blend beef patty on a brioche bun with veal bacon, American cheese, and a special sauce built from pickles and dijon.", dropLine: "woodfire grilled burger with veal bacon and special sauce", ingredients: "special sauce- pickles, chili flakes, olive oil, ketchup, dijon mustard, mayo.  Garnish- french fries, ketchup. Veal bacon- same as app.", chefPrep: "burger build- grilled brioche bun, grilled veal bacon, special sauce, grilled house blend prime beed patty, bib lettuce, american cheese, tomato, olive oil.", allergensInRecipe: ["chili", "mustard", "eggs", "gluten", "dairy", "vinegar"], allergensRemovable: ["eggs", "vinegar", "mustard"] },
  { id: "d-branzino", name: "Salt-Grilled Branzino", section: "Entrées", description: "Fresh herb salad, brown butter, lemon", pairedWineIds: ["w4", "w7", "w10"], quizClue: "A whole Mediterranean sea bass, deboned and cooked until the skin turns crackling crisp, finished with charred lemon and an herb salad.", dropLine: "crispy skin branzino with grilled lemon and herb salad", ingredients: "branzino- salt, pepper, grilled lemon. Herb salad- chives, parsley, basil, black radish, red radish, lemon agrumato olive oil, salt, pepper", chefPrep: "fresh whole branzino fully deboned, seasoned with salt, pepper and grilled until crispy skin and moist flesh. Garnished with grilled lemon and herb salad.", allergensInRecipe: ["fish", "citrus"], allergensRemovable: ["citrus"] },
  { id: "d-wagyu-skirt", name: "Wagyu Skirt Steak", section: "Entrées", description: "Fourme d'Ambert cheese, compressed peppers, chili vinaigrette", pairedWineIds: ["w6", "w11", "w19"], quizClue: "A marinated cut of beef finished with star anise and ginger, grilled and sliced, plated over a chili-pepper vinaigrette with poblano and red bell pepper.", dropLine: "Grilled wagyu skirt steak with chili pepper vinaigrette", ingredients: "skirt steak marinade- star anise, black pepper, chili flakes, garlic, ginger, rice vinegar, mirin, gluten free soy sauce, olive oil. Chili pepper vinaigrette- pequillo peppers, guajillo peppers, apple cider vinegar, sugar, salt, shallots, garlic, cayenne, olive oil. marinated peppers- poblanos, red bell peppers, sherry vinegar.  Garnish- cilantro, Fourme d'Ambert blue cheese, saba vinegar, Maldon salt, olive oil", chefPrep: "marinated skirt steak grilled until desired temp and cut into bite size pcs. On a plate chili pepper vinaigrette, poblano and red belle pepper placed. Follow by sliced steak, blue cheese, cilantro, saba vinegar, salt and olive oil.", allergensInRecipe: ["chili", "garlic", "onion", "vinegar", "alcohol", "soy", "dairy"], allergensRemovable: ["dairy"] },
  { id: "d-short-rib", name: "Grilled Bone-in Short Rib", section: "Entrées", description: "Chimichurri, garlic breadcrumbs", pairedWineIds: ["w11", "w12", "w13", "w14", "w18", "w19"], quizClue: "A slow-braised cut of beef, seared first then cooked for hours with red wine, root vegetables, and tomato paste until fall-apart tender.", dropLine: "", ingredients: "short rib glaze- shallots, garlic, bay leaf, thyme, olive oil, red wine vinegar, red wine, water, carrots, celery, onion, salt, pepper, tomato paste. Chimichurri- same as side chimichurri.", chefPrep: "short ribs seasoned with salt, pepper and seared hard. Then all vegetables added with tomato paste and cooked until soft. Covered with foil and braised for 3 hours. Then grilled until caramalized , glazed with short rib glaze and garnished with chimichurri.", allergensInRecipe: ["garlic", "onion", "vinegar", "alcohol", "chili"], allergensRemovable: ["chili"] },
  { id: "d-marinated-chicken", name: "Marinated Chicken", section: "Entrées", description: "Espelette, crispy baby potatoes, spicy aioli", pairedWineIds: ["w11", "w13", "w12", "w17"], quizClue: "A whole young bird cured overnight in lemon, espelette pepper, and oregano, grilled skin-side down and finished over cedar, served with double-fried potatoes and a spicy aioli.", dropLine: "grilled baby chicken with double fried potatoes and spicy aioli", ingredients: "baby chicken marinade- lemon juice, olive oil, espelette pepper, oregano, garlic, salt, pepper. Potato cooking liquid- water, thyme, garlic, bay leaf, chili flakes, salt. Garnish- spicy mayo, chervil, chives", chefPrep: "marinated chicken grilled first skin side down on the grill then placed in cedar wood and cooked in Jasper until fully cooked and juice. Potatoes are smashed after first cook and deep fried until cripsy on the pick up. Seasoned with salt. Served with spicy mayo on the side with chives", allergensInRecipe: ["citrus", "chili", "garlic", "onion", "eggs"], allergensRemovable: ["eggs", "onion"] },

  { id: "d-tuna-sushi", name: "Tuna (Maguro / Akami / Chutoro / Otoro)", section: "Sushi", description: "Sashimi and nigiri, 2 pieces per order", pairedWineIds: ["w20"] },
  { id: "d-hamachi", name: "Hamachi", section: "Sushi", description: "Other fish, sashimi and nigiri", pairedWineIds: ["w9", "w20"] },
  { id: "d-chefs-nigiri", name: "Chef's Selection of Nigiri", section: "Sushi", description: "Chef's choice, 3/6/9/12 pieces", pairedWineIds: ["w10", "w20"], quizClue: "Five, seven, or ten pieces of the freshest hand-pressed fish of the day, served with fresh grated wasabi.", dropLine: "chefs choice of nigiri selection", ingredients: "seasoned sushi rice, fresh grated wasabi, seasonal garnishes", chefPrep: "chefs choice of 5,7 and 10 pcs of freshest daily nigiri selection served with, fres grated wasabi.", allergensInRecipe: ["fish", "vinegar", "shellfish", "mustard"], allergensRemovable: ["shellfish", "mustard"] },
  { id: "d-sashimi-platter", name: "Premium Sashimi Platter", section: "Sushi", description: "Chef's choice variations", pairedWineIds: ["w20"], quizClue: "A choice of 5, 9, or 12 kinds of the day's freshest raw cuts, served over crushed ice with daikon and shiso.", dropLine: "sashimi platter with traditional garnishes", ingredients: "fish might include in the platter- maguro (yellowfin tuna, akami (lean bluefin tuna), chutoro (medium fatty bluefin tuna), otoro (fattiest part of bluefin tuna) scottish salmon, fresh oysters with ponzu,  ikura (marinated salmon eggs), madai (red sea bream), continued on omasake platter discription", chefPrep: "chefs choice of 5,9 and 12 kinds of freshest daily sashimi selection served with, daikon, shiso leaves and other garnished over crushed ice and light underneath. Served 2 pc fish per kind.", allergensInRecipe: ["fish", "shellfish", "soy", "gluten"], allergensRemovable: ["soy", "gluten", "shellfish"] },
  { id: "d-omakase-platter", name: "Prime 131 Omakase Platter", section: "Sushi", description: "14 pcs sashimi, 14 pcs nigiri, choice of 3 specialty rolls", pairedWineIds: ["w20"], quizClue: "The kitchen's highest-end tasting experience: 14 pieces of raw fish, 14 hand-pressed pieces, and three specialty maki of your choosing.", dropLine: "Prime 131 premium omakase platter", ingredients: "shima aji (stripped jack), uni (sea urchin roe), botan ebi (peony sweet shrimp), hotate (scallop), ebi (tiger prawn),  tobiko (flying fish roe), tamago (egg), uzura (quail egg), hamachi (yellowtail), unagi (fresh water eel)", chefPrep: "chef’s selection of highest end 14 pcs sashimi, 14 pcs nigiri, 3 specialty rolls (guests choice)", allergensInRecipe: ["shellfish", "fish", "eggs", "soy", "gluten", "sesame"], allergensRemovable: ["eggs", "gluten", "sesame", "soy", "shellfish"] },
  { id: "d-sushi-sashimi-nigiri", name: "Sashimi & Nigiri (general)", section: "Sushi", description: "Full sashimi and nigiri program", pairedWineIds: ["w20"] },
  { id: "d-ikura", name: "Ikura", section: "Sushi", description: "House marinated ikura with fresh wasabi and nori", pairedWineIds: ["w20"], quizClue: "Premium Japanese salmon roe marinated in sake, mirin, and soy until the fishy edge mellows, served over warm rice with nori.", dropLine: "house marinated ikura with fresh wasabi and nori", ingredients: "marinated ikura- sake, mirin, soy sauce, premium japanese salmon eggs. Ikura nigiri- fresh grated wasabi, seasoned sushi rice, nori seaweed, marinated ikura", chefPrep: "for marinated ikura, alcohol is burned off from the sake and mirin, then soy sauce is added and cooled down. Salted salmon eggs are washed well under cold water and marinated until the fishy, salty flavor mellows. Nigiri must be consumed right away for the warm rice and crispy nori experience.", allergensInRecipe: ["alcohol", "fish", "soy", "gluten", "mustard"], allergensRemovable: ["mustard"] },
  { id: "d-tamagoyaki", name: "Tamagoyaki", section: "Sushi", description: "Housemade tamagoyaki (Japanese sweet omelette)", pairedWineIds: ["w20"], quizClue: "A Japanese rolled omelette layered slowly in a rectangular pan, sweetened with dashi and mirin, served warm over rice.", dropLine: "housemade tamagoyaki (japanese sweet omelette)", ingredients: "tamagoyaki mix- dashi, mirin, sake, soy sauce, salt, sugar, oil. Dashi- water, bonito flakes, konbu. Tamago nigiri- fresh wasabi, nori, seasoned sushi rice", chefPrep: "all ingredients are mixed well and strained through a fine chinois, then cooked in a Japanese omelette pan layer by layer. Cooled completely before serving.", allergensInRecipe: ["fish", "alcohol", "soy", "gluten", "eggs", "mustard"], allergensRemovable: ["mustard"] },
  { id: "d-unagi", name: "Unagi", section: "Sushi", description: "Grilled fresh water eel with sweet soy sauce", pairedWineIds: ["w20"], quizClue: "Fresh water eel roasted and caramelized in a sweet soy glaze, served warm over rice.", dropLine: "grilled fresh water eel with sweet soy sauce", ingredients: "cooked unagi- japanese fresh water eel roasted with soy sauce, mirin, sugar. Unagi nigiri- fresh wasabi, nori, seasoned sushi rice", chefPrep: "fresh water eel is roasted with eel sauce until fully cooked and caramelized. For nigiri service it's heated until warm and served on top of the rice with fresh wasabi, wrapped with nori, and garnished with more eel sauce.", allergensInRecipe: ["fish", "soy", "alcohol", "gluten", "mustard"], allergensRemovable: ["mustard"] },

  { id: "d-prime131-roll", name: "Prime 131 Roll", section: "Sushi Rolls", description: "A5 wagyu, foie gras, shrimp tempura, avocado, shiso, yuzu aioli, eel sauce", pairedWineIds: [], quizClue: "A specialty maki packed with shrimp tempura, seared foie gras, and sliced A5 wagyu, finished with a yuzu aioli and eel sauce.", dropLine: "Prime 131 roll with A5 wagyu and foie gras", ingredients: "Prime 131 roll- shrimp tempura, foie gras, A5 japanese wagyu, avocado, shiso, yuzu aioli, eel sauce. Yuzu aioli- mayo, ponzu, rice vinegar, salt, lemon juice, yuzu kosho, garlic confit.", chefPrep: "seasoned sushi rice spread on nori and filled with shrimp tempura,seared foie gras, avocado, shiso and  rolled. Then topped with sliced A5 wagyu and cut into 8 equal pcs. Seated until medium rare. Garnished with yuzu kosho aioli and eel sauce.", allergensInRecipe: ["shellfish", "fish", "eggs", "garlic", "gluten", "soy", "citrus", "alcohol", "vinegar"], allergensRemovable: [] },
  { id: "d-crunchy-spicy-tuna-roll", name: "Crunchy Spicy Tuna Roll", section: "Sushi Rolls", description: "Avocado, tama arare, kaiware, sweet soy sauce", pairedWineIds: ["w5"], quizClue: "A maki built on a chopped yellowfin mix, avocado, and crispy rice puffs, dressed with a fiery mayo and sweet eel sauce.", dropLine: "crunchy spicy tuna roll with avocado and eel sauce", ingredients: "crunchy spicy tuna roll- sushi rice, nori, tuna mix, avocado, tama arare, kaiware (radish sprouts), spicy mayo, eel sauce, sesame seeds. Tuna mix- tuna, scallions, shallots, kimchi sauce,  yuzu juice, eel sauce, ponzu, sriracha. Spicy mayo- japanese mayo, togarashi, sesame oil, chili oil, ponzu, yuzu juice, salt. Eel sauce- soy sauce, sugar, mirin, starch.", chefPrep: "sushi rice spreaded evenly on the nori and sprinkled sesame seeds. Then inside the roll placed tuna mix, tama arare, avocado, kaiware and closed. Then cut 8 equal garnished with, spicy mayo and eel sauce", allergensInRecipe: ["fish", "onion", "chili", "citrus", "soy", "sesame", "alcohol", "eggs", "gluten", "vinegar"], allergensRemovable: ["eggs"] },
  { id: "d-dragon-roll", name: "Dragon Roll", section: "Sushi Rolls", description: "Shrimp tempura, jumbo lump crab salad, mango, avocado, sriracha", pairedWineIds: [], quizClue: "A maki filled with shrimp tempura, lump crab salad, and mango, topped with avocado and a spicy mayo drizzle.", dropLine: "dragon roll with shrimp tempura and crab salad", ingredients: "dragon roll- shrimp tempura, jumbo lump crab salad, mango, spicy mayo, avocado, sriracha, seasoned sushi rice, nori,sesame seeds. Shrimp tempura- salt, whole eggs, flour, tiger shrimp, soda water. Crab salad- Maryland blue crab, lemon juice, lemon zest, spicy mayo, salt.", chefPrep: "seasoned sushi rice spread on nori and filled with hot shrimp tempura, crab salad, mango,  rolled. Then topped with avocado and cut into 8 equal pcs. Garnished with spicy mayo, sriracha", allergensInRecipe: ["shellfish", "eggs", "gluten", "sesame", "chili", "citrus", "soy", "alcohol"], allergensRemovable: [] },
  { id: "d-yellowtail-serrano-roll", name: "Yellowtail Serrano Roll", section: "Sushi Rolls", description: "Cucumber, kizami wasabi, scallions, wasabi mayo", pairedWineIds: [], quizClue: "A maki of hamachi, cucumber, and pickled wasabi, topped with a thin sliced chili pepper and wasabi mayo.", dropLine: "yellowtail serrano roll with cucumber and wasabi mayo", ingredients: "yellowtail serrrano roll- seasoned sushi rice, nori, sesame seeds, hamachi, cucumber, kizami wasabi, scallions. Garnish- serrano pepper, wasabi mayo, micro greens. Kizami wasabi- wasabi, horseradish, soy sauce, sugar, oil. Wasabi mayo- wasabi, mayo, lemon juice, salt", chefPrep: "seasoned sushi rice spread on nori and filled with hamachi, cucumber, kizami wasabi, scallions and  rolled. Then  cut into 8 equal pcs. Garnished with serrano pepper, wasabi mayo and micro greens", allergensInRecipe: ["fish", "onion", "mustard", "soy", "chili", "eggs", "citrus", "sesame", "gluten"], allergensRemovable: ["chili", "citrus", "eggs", "gluten", "onion", "sesame", "soy", "mustard"] },
  { id: "d-seared-spicy-salmon-roll", name: "Seared Spicy Salmon Tartare Roll", section: "Sushi Rolls", description: "Spiced salmon mix, seared salmon, spicy aioli, ponzu, arare", pairedWineIds: ["w3"] },
  { id: "d-negi-toro-roll", name: "Negi Toro Roll", section: "Sushi Rolls", description: "Fatty tuna, finely diced scallions", pairedWineIds: ["w11"], quizClue: "A maki of fatty bluefin belly and scallions, wrapped seaweed-side out and served simply, with optional roe on top.", dropLine: "Toro and scallions roll", ingredients: "negi toro roll- bluefin otoro, scallions, sesame seeds, nori, seasoned sushi rice, optional caviar can be added for additional charge. Seasoned sushi rice- rice vinegar, salt, sugar, konbu seaweed, highest quality koshikiharu rice", chefPrep: "seasoned sushi rice spread on nori and filled with bluefin toro, scallions and  rolled into 8 equal pcs. Served seaweed outside", allergensInRecipe: ["fish", "onion", "sesame", "vinegar"], allergensRemovable: ["onion", "sesame"] },
  { id: "d-131-california-roll", name: "131 California Roll", section: "Sushi Rolls", description: "Lump crab, cucumber, avocado, tobiko, spicy mayo", pairedWineIds: ["w5"], quizClue: "A classic maki of king crab, avocado, and cucumber under a spicy mayo, finished with orange tobiko and fresh lemon.", dropLine: "Premium california roll with fresh blue crab.", ingredients: "premium california roll- seasoned sushi rice, nori, avocado, ble crab meat, cucumber, spicy mayo.Garnish- orange tobiko, fresh lemon juice.", chefPrep: "seasoned sushi rice spread on nori and filled with avocado, king crab, cucumber, spicy mayo. Rolled and cut into 8 equal pcs.", allergensInRecipe: ["shellfish", "eggs", "citrus", "fish", "chili", "soy"], allergensRemovable: ["chili", "citrus", "eggs", "fish", "soy"] },
  { id: "d-miso-salmon-roll", name: "Miso Salmon Roll", section: "Sushi Rolls", description: "Kanpyo, asparagus tempura, avocado, truffle oil, ponzu", pairedWineIds: [], quizClue: "A maki of sweet gourd shavings, tempura asparagus, and avocado, topped with a Scottish-raised fish, truffle oil, and a sweet glaze.", dropLine: "miso salmon roll with asparagus tempura and ponzu", ingredients: "miso salmon roll- kanpyo (sweet gourd shavings), tempura asparagus, avocado, seasoned sushi rice, nori. Garnish- scottish salmon, truffle oil, teriyaki miso (same as black cod marinade), ponzu, micro greens", chefPrep: "seasoned sushi rice spread on nori and filled with avocado, kanpyo, tempura asparagus and  rolled into 8 equal pcs. Then sliced salmon placed on top of the roll, brushed with truffle oil and torched. Garnished with teriyaki miso sauce, micro greens and ponzu", allergensInRecipe: ["fish", "garlic", "gluten", "sesame", "soy", "alcohol", "citrus", "vinegar"], allergensRemovable: ["sesame"] },
  { id: "d-sushi-rolls", name: "Sushi Rolls (general)", section: "Sushi Rolls", description: "Full sushi roll program", pairedWineIds: ["w20"] },

  { id: "d-mashed-potato", name: "Loaded Mashed Potato", section: "Sides", description: "Short ribs, raclette, truffle jus", pairedWineIds: ["w6"], quizClue: "A creamy Idaho root vegetable, warmed with braised short rib and heavy cream, topped with melted raclette.", dropLine: "mash potatoes with reclette cheese and truffle jus", ingredients: "mash potato- idaho potato, heavy cream, butter, salt. Truffle jus- veal demi, red vine, shallots, garlic, salt, pepper, olive oil, black truffles. Garnished with reclette cheese, braised short ribs, chives", chefPrep: "mash potatoes heat up with braised short ribs and heavy cream. Then transferred into serving dish, topped with reclette cheese and melted in the salamander. Garnished with chives and truffe jus served tableside like souffle.", allergensInRecipe: ["dairy", "garlic", "onion", "alcohol"], allergensRemovable: ["alcohol", "garlic", "onion"] },
  { id: "d-wild-mushrooms", name: "Exotic Wild Mushrooms", section: "Sides", description: "Pickled shallot, herbs, breadcrumbs", pairedWineIds: ["w17"] },
  { id: "d-mac-cheese", name: "Ricotta Stuffed Mac & Cheese", section: "Sides", description: "Toasted bread crumbs, parsley", pairedWineIds: ["w6"], quizClue: "Large pasta shells filled with a soft Italian curd, bathed in a sharp cheddar cream sauce and topped with toasted breadcrumbs.", dropLine: "", ingredients: "cheese sauce- garlic, shallots, heavy cream, ap flour, butter, white sharp cheddar, salt. Pasta- big shell pasta, ricotta, salt. Garnish- toasted breadcrumbs, parsley", chefPrep: "big shell pasta blanched in salt water untill cooked and cooled down, then stuffed with ricotta and set a side for service. During service when order comes in paste covered with warm cheese sauce and heat up in the oven until hot. Garnished with breadcrumbs and parsley", allergensInRecipe: ["dairy", "garlic", "onion", "gluten"], allergensRemovable: [] },
  { id: "d-asparagus", name: "Grilled Asparagus", section: "Sides", description: "Ricotta, mojo rojo", pairedWineIds: [], quizClue: "Green spears cooked over the wood fire, plated with whipped ricotta and a red-pepper mojo rojo vinaigrette.", dropLine: "grilled asparagus with whipped ricotta and mojo rojo", ingredients: "mojo rojo vinaigrette- bell pepper, fresno pepper, cilantro, red onion, garlic, cumin caraway seeds, olive oil, red wine vinegar, salt, pepper, honey. Garnish- mint, micro basil, olive oil. Whipped ricotta- same as dip", chefPrep: "asparagus grilled on wood fire until nice color. Plated with whipped ricotta, mojo rojo vinaigrette, garnishes. Gluten free great sharing item.", allergensInRecipe: ["chili", "dairy", "garlic", "onion", "vinegar"], allergensRemovable: [] },
  { id: "d-fries", name: "French Fries", section: "Sides", description: "Parsley, spicy aioli", pairedWineIds: [], quizClue: "Thick-cut potatoes cooked in hot oil until crispy, seasoned simply, and served with a jalapeño aioli.", dropLine: "french fries with parsley and jalapeno aioli", ingredients: "jalapeno aioli- mayo, cilantro, jalapeno, garlic, lime juice, cumin, salt. Garnish- parsley, salt, pepper.", chefPrep: "thick cut french fries fried until crispy and seasoned with salt, peppper. Served with Jalapeno aioli on the side", allergensInRecipe: ["chili", "citrus", "eggs", "garlic"], allergensRemovable: ["chili", "citrus", "eggs", "garlic"] },
  { id: "d-broccolini", name: "Grilled Broccolini", section: "Sides", description: "Lemon-chili vinaigrette", pairedWineIds: [], quizClue: "A slender green vegetable blanched, then finished on the wood fire with a chili-lemon vinaigrette and crispy rice puffs.", dropLine: "grilled broccolini with lemon chili vinaigrette", ingredients: "broccolini- chili lemon vinaigrette, crispy rice puffs, olive oil, salt, pepper. Chili lemon vinaigrette- japanese chili flakes, shallots, lemon juice + zest, lime juice + zest, water, olive oil, sugar, salt, apple cider vinegar.", chefPrep: "broccolini cleaned, blanched and set a side for service. During service its seasoned with olive oil, salt, pepper and grilled on woodfire. Then dressed with chili lemon vinaigrette and garnished with puffed rice crakers.", allergensInRecipe: ["chili", "citrus", "onion", "vinegar"], allergensRemovable: [] },
  { id: "d-spinach-gratin", name: "Spinach Gratin", section: "Sides", description: "Parmesan, garlic herb bread crumbs", pairedWineIds: [] },

  { id: "d-tenderloin-8", name: "8oz American Tenderloin (Wagyu)", section: "Steaks", description: "Choice of live post oak, pecan, or bourbon wood", pairedWineIds: ["w19"], quizClue: "An 8-ounce, most-tender cut from a domestic gold-grade beef program, finished with rendered fat and garlic confit.", dropLine: "8 oz SRF gold tenderloin with garlic confit", ingredients: "8 oz Snake river farms gold grade tenderloin- salt, pepper, rendered A5 wagyu fat, garlic confit (garlic, oil)", chefPrep: "hightest grade american wagyu steak seasoned with salt and pepper and cooked on wood fire grill with choice of wood to desired temperature. Served with garlic confit on the side and brushed with rendered A5 wagyu fat right before serving", allergensInRecipe: ["garlic"], allergensRemovable: ["garlic"] },
  { id: "d-ny-strip-12", name: "12oz American NY Strip (Wagyu)", section: "Steaks", description: "Choice of live post oak, pecan, or bourbon wood", pairedWineIds: [], quizClue: "A 12-ounce cut from the short loin, domestic gold-grade beef, finished with rendered fat and garlic confit.", dropLine: "12 oz SRF gold NY strip with garlic confit", ingredients: "12 oz Snake river farms gold grade NY strip- salt, pepper, rendered A5 wagyu fat, garlic confit (garlic, oil). Snake River Farms American Wagyu is a cross between purebred Japanese Wagyu and high-quality American cattle.", chefPrep: "SRF Black Label™ and SRF Gold Label™ both score above USDA Prime: SRF Silver Label™ has a BMS of 4 to 5 with similar marbling to USDA Prime grade beef. SRF Black Label™ has a BMS of 6 to 8 with significantly more marbling than USDA Prime grade beef.  SRF Gold Label™ registers a BMS of 9 or higher and contains the highest level of marbling we offer.", allergensInRecipe: ["garlic"], allergensRemovable: ["garlic"] },
  { id: "d-ribeye", name: "18oz American Ribeye (Wagyu)", section: "Steaks", description: "Choice of live post oak, pecan, or bourbon wood", pairedWineIds: ["w14"], quizClue: "A well-marbled cut from the rib section, domestic gold-grade beef, finished with rendered fat and garlic confit.", dropLine: "10 oz SRF gold ribeye with garlic confit", ingredients: "10 oz Snake river farms gold grade ribeye- salt, pepper, rendered A5 wagyu fat, garlic confit (garlic, oil)", chefPrep: "hightest grade american wagyu steak seasoned with salt and pepper and cooked on wood fire grill with choice of wood to desired temperature. Served with garlic confit on the side and brushed with rendered A5 wagyu fat right before serving", allergensInRecipe: ["garlic"], allergensRemovable: ["garlic"] },
  { id: "d-ny-strip-14", name: "14oz Australian NY Strip (Wagyu)", section: "Steaks", description: "Choice of live post oak, pecan, or bourbon wood", pairedWineIds: ["w14"], quizClue: "A 14-ounce cut from the short loin, graded 9+ from a Southern Hemisphere high-marbling program, finished with rendered fat and garlic confit.", dropLine: "14 oz Australian NY strip with garlic confit", ingredients: "14 oz 9+ highest grade Australian wagyu NY strip- salt, pepper, rendered A5 wagyu fat, garlic confit (garlic, oil). Marbling is graded on a scale of 0-9 in the Ausmeat grading system. The Japanese grading system goes up to 12.   Sher Wagyu bodies well above MS 9 are graded as MS 9+.", chefPrep: "hightest grade australian wagyu Sher Farms steak seasoned with salt and pepper and cooked on wood fire grill with choice of wood to desired temperature. Served with garlic confit on the side and brushed with rendered A5 wagyu fat right before serving. The Sher Wagyu Fullblood cattle are based on the three main Japanese bloodlines of Tajima, Fujiyoshi and Kedaka. The Tajima bloodline is based on the Yasumi doi and Kikunori doi lines.", allergensInRecipe: ["garlic"], allergensRemovable: ["garlic"] },
  { id: "d-tomahawk", name: "32oz Australian Tomahawk (Wagyu)", section: "Steaks", description: "Choice of live post oak, pecan, or bourbon wood", pairedWineIds: ["w16"], quizClue: "A 32-ounce, bone-in cut from the rib section with the full rib bone left on for presentation, graded 9+ from a Southern Hemisphere high-marbling program.", dropLine: "32 oz Australian wagyu tomahawk with garlic confit", ingredients: "32 oz 9+ highest grade Australian wagyu tomahawk- salt, pepper, rendered A5 wagyu fat, garlic confit (garlic, oil). Cattle are pasture fed until 18 months of age , then grainfed for 400+ days to create a delicious and consistent Wagyu product for you to enjoy.", chefPrep: "Sher Wagyu beef is all natural, hormone and antibiotic free and Halal accredited. All Sher Wagyu Fullblood cattle are traceable back to their Japanese ancestors and are DNA registered with pedigrees of sires & dams kept on the AWA data base.Nick and Vicki Sher calved the first Purebred Wagyu embryo calf in Australia on February 11, 1992. Sher Wagyu’s Fullblood herd is based at Ballan, central Victoria.", allergensInRecipe: ["garlic"], allergensRemovable: ["garlic"] },
  { id: "d-kagawa-a5", name: "4oz Japanese A5 Wagyu Kagawa Olive Beef Tenderloin", section: "Steaks", description: "Choice of live post oak, pecan, or bourbon wood", pairedWineIds: [], quizClue: "A 4-ounce, ultra-rare cut from cattle fed a special island diet that includes a fruit byproduct, giving the fat an unusually nutty character.", dropLine: "Premium Kagawa olive beef with garlic confit", ingredients: "Sanuki olive beef - salt, pepper, rendered A5 wagyu fat, garlic confit (garlic, oil). There are only 1,700 Sanuki cattle on the island, all of which are fed a special type of feed featuring a dehydrated and roasted mulch of olives. This produces the rich, tender texture of Olive Wagyu beef, which has higher levels of oleic acid and yellowed fat, creating a slightly nutty taste.", chefPrep: "Sanuki Live Wagyu originated in the Kagawa Prefecture of Japan. More specifically, Shodoshima Island, which is known for producing 99% of Japan's olive oil. While raising wagyu cattle for meat production started back in 1882, in the early 20th century, Shodoshima began its mass production of olive oil. Local cattle rancher, Masaki Ishii, was tired of seeing all the olive waste simply thrown out. So, instead, he started feeding this pulp to his heard of black wagyu cattle – resulting in the first olive-fed wagyu in 2011.", allergensInRecipe: ["garlic"], allergensRemovable: ["garlic"] },

  { id: "d-steak-sauce", name: "Prime 131 Steak Sauce", section: "Sauces", description: "House made steak sauce", pairedWineIds: [], quizClue: "A house-made condiment built on ketchup, sherry vinegar, molasses, and Worcestershire, finished with black garlic and yuzu juice.", dropLine: "house made steak sauce", ingredients: "steak sauce- ketchup, sherry vinegar, worcestershire sauce, molasses, black pepper, salt, saba vinegar, ancho powder, black garlic, yuzu juice. worcestershire sauce- vinegar, water, molasses, sugar, salt, anchovy, celery seed, garlic, tamarind. saba vinegar- grapes, red wine vinegar", chefPrep: "All ingredients mixed well and set aside for service. Served room temperature.", allergensInRecipe: ["vinegar", "chili", "garlic", "citrus", "fish"], allergensRemovable: [] },
  { id: "d-chimichurri", name: "Chimichurri Sauce", section: "Sauces", description: "House made chimichurri sauce", pairedWineIds: [], quizClue: "A bright, herbaceous condiment of parsley, cilantro, capers, and red wine vinegar with a touch of chili flake, the classic partner for steak and chicken.", dropLine: "house made chimichurri sauce", ingredients: "chimichurri- parsley, cilantro, capers, red wine vinegar, salt, toasted chili flakes, black pepper, sunflower oil", chefPrep: "All ingredients mixed well in the bowl and kept at room temperature for service. A great condiment for steaks and chicken.", allergensInRecipe: ["vinegar", "chili"], allergensRemovable: [] },
  { id: "d-truffle-butter", name: "Truffle Butter", section: "Sauces", description: "House made fresh truffle butter", pairedWineIds: [], quizClue: "Whipped until airy, then finished with a rare black fungus and its own fragrant oil, rolled into a log and chilled.", dropLine: "House made fresh truffle butter", ingredients: "truffle butter- fresh black truffles, butter, white truffle oil, salt", chefPrep: "Room temperature butter whipped until airy, then salt, microplaned fresh black truffles, and truffle oil are added. Rolled into a torchon and kept cold for service.", allergensInRecipe: ["dairy"], allergensRemovable: [] },
  { id: "d-filet-8", name: "8oz Filet (Classics)", section: "Steaks", description: "Choice of live post oak, pecan, or bourbon wood", pairedWineIds: ["w15"], quizClue: "An 8-ounce cut from the most tender part of the animal, seasoned simply and finished with garlic confit.", dropLine: "8 oz Prime filet with garlic confit", ingredients: "8 oz fliet- salt, pepper, rendered A5 wagyu fat, garlic confit (garlic, oil).Less than 2% of all beef produced in the United States will earn the top prime designation.", chefPrep: "steak seasoned with salt and pepper and cooked on wood fire grill with choice of wood to desired temperature. Served with garlic confit on the side and brushed with rendered A5 wagyu fat right before serving", allergensInRecipe: ["garlic"], allergensRemovable: ["garlic"] },
  { id: "d-bone-in-filet", name: "12oz Bone-In Filet (Classics)", section: "Steaks", description: "Choice of live post oak, pecan, or bourbon wood", pairedWineIds: ["w15", "w18"], quizClue: "A 12-ounce tender cut left attached to part of the rib for extra flavor, seasoned simply and finished with garlic confit.", dropLine: "12 oz Prime bone in filet with garlic confit", ingredients: "12 oz bone in fliet- salt, pepper, rendered A5 wagyu fat, garlic confit (garlic, oil). The word \\\"prime\\\" is a quality grade assigned by the U.S. Department of Agriculture to describe the highest quality beef and other meats, including veal and lamb, in terms of tenderness, juiciness, and flavor.", chefPrep: "steak seasoned with salt and pepper and cooked on wood fire grill with choice of wood to desired temperature. Served with garlic confit on the side and brushed with rendered A5 wagyu fat right before serving", allergensInRecipe: ["garlic"], allergensRemovable: ["garlic"] },
  { id: "d-ny-strip-16", name: "16oz USDA Prime NY Strip (Classics)", section: "Steaks", description: "Choice of live post oak, pecan, or bourbon wood", pairedWineIds: ["w16"], quizClue: "A 16-ounce cut from the short loin, graded top-tier by the federal beef grading system, seasoned simply and finished with garlic confit.", dropLine: "16 oz prime NY strip with garlic confit", ingredients: "16 oz NY strip- salt, pepper, rendered A5 wagyu fat, garlic confit (garlic, oil). Marbling- the term used to describe flecks of fat within the meat, adds flavor, and younger beef produces the most tender meat.", chefPrep: "steak seasoned with salt and pepper and cooked on wood fire grill with choice of wood to desired temperature. Served with garlic confit on the side and brushed with rendered A5 wagyu fat right before serving", allergensInRecipe: ["garlic"], allergensRemovable: ["garlic"] },
  { id: "d-porterhouse", name: "USDA Prime Porterhouse for Two (Classics)", section: "Steaks", description: "Choice of live post oak, pecan, or bourbon wood", pairedWineIds: ["w16"], quizClue: "A 40-ounce cut combining two different muscles on either side of a T-shaped bone, graded top-tier by the federal beef grading system, built to share.", dropLine: "40 oz Prime porterhouse for 2 with garlic confit", ingredients: "40 oz Porterhouse- salt, pepper, rendered A5 wagyu fat, garlic confit (garlic, oil). anything receiving a prime designation is deemed to be the best of the best.", chefPrep: "steak seasoned with salt and pepper and cooked on wood fire grill with choice of wood to desired temperature. Served with garlic confit on the side and brushed with rendered A5 wagyu fat right before serving", allergensInRecipe: ["garlic"], allergensRemovable: ["garlic"] }
];

const STYLE_LABELS = {
  sparkling: "Sparkling",
  white: "Whites & Rosés",
  red: "Reds",
  dessert: "Dessert",
  sake: "Sake"
};

const STYLE_ORDER = ["sparkling", "white", "red", "dessert", "sake"];
const SECTION_ORDER = ["Raw Bar", "Starters", "Soups & Salads", "Entrées", "Sushi", "Sushi Rolls", "Sides", "Steaks", "Sauces"];

const COCKTAILS = [
  {
    id: "c1", name: "Lycheetini", glassware: "Martini", method: "Shake & Strain",
    flavorTags: ["Lychee", "Citrus", "Floral", "Sweet"],
    ingredients: ["2 oz Haku Vodka", "1 oz Re\u00e0l Lychee", "1 oz Finest Call Single Pressed Lemon Juice"],
    garnish: "Popping Boba Pearls",
    directions: "Combine all ingredients in a cocktail shaker with ice. Shake and strain into martini glass. Garnish and serve.",
    prep: "", funFact: "Haku Vodka is filtered through bamboo charcoal, a Japanese technique that gives it an unusually silky, soft texture for a vodka.", bestFor: "A guest who wants something playful and not too boozy-tasting to open the night."
  },
  {
    id: "c2", name: "Tequila Twilight", glassware: "Double Rocks", method: "Shake & Strain",
    flavorTags: ["Dragon Fruit", "Papaya", "Lime", "Agave"],
    ingredients: ["1.5 oz Casamigos Blanco", "0.5 oz Cointreau Orange Liqueur", "1 oz Finest Call Single Pressed Lime Juice", "1 oz Sweetbird Dragon Fruit & Papaya Syrup"],
    garnish: "Dehydrated Dragon Fruit, Mint Sprig",
    directions: "Combine all ingredients in a cocktail shaker with ice. Shake and strain over fresh ice into Rocks Glass. Garnish and serve.",
    prep: "", funFact: "Casamigos was founded in 2013 by George Clooney and two friends — the name translates to &ldquo;house of friends.&rdquo;", bestFor: "A tequila drinker who wants something bright and tropical, not smoky or agave-forward."
  },
  {
    id: "c3", name: "Yuzu Basil Martini", glassware: "Martini", method: "Shake & Strain",
    flavorTags: ["Yuzu", "Ginger", "Basil", "Bright Citrus"],
    ingredients: ["2 oz Ketel One Vodka", "0.5 oz Finest Call Single Pressed Lemon Juice", "0.5 oz Finest Call Single Pressed Lime Juice", "0.75 oz Yuzu & Ginger Puree (house prep)", "4 Basil Leaves (torn in half)"],
    garnish: "Basil Leaf, Fresh or Dehydrated Lemon Wheel",
    directions: "Combine all ingredients in a cocktail shaker with ice. Shake and strain into martini glass. Garnish and serve.",
    prep: "Yuzu Ginger Puree: whisk or blend 1 bottle (16.9 oz) Re\u00e0l Yuzu with 1 bottle (16.9 oz) Re\u00e0l Ginger for 3-5 minutes until fully emulsified. Label, date, refrigerate. Shake well before use. Yields 33.8 oz.", funFact: "Yuzu is a Japanese citrus prized more for its fragrance than its tartness — it shows up as often in high-end cocktails as it does in Japanese kitchens.", bestFor: "A guest who finds a classic martini too austere and wants something more aromatic."
  },
  {
    id: "c4", name: "Negroni Bianco", glassware: "Rocks Glass", method: "Stir & Strain",
    flavorTags: ["Bergamot", "Floral", "Herbal", "Bittersweet"],
    ingredients: ["1 oz Bombay Dry Gin", "1 oz Italicus", "1 oz Cinzano Bianco Vermouth"],
    garnish: "Large Format Ice, Lemon Peel, Rosemary Sprig",
    directions: "Stir all ingredients in a mixing glass with ice. Strain over large format ice cube. Garnish and serve.",
    prep: "", funFact: "Italicus is a modern bergamot liqueur, launched in 2016 and credited with reviving interest in Italian aperitivo culture outside Italy.", bestFor: "A Negroni drinker who wants something lighter and more floral than the classic red version."
  },
  {
    id: "c5", name: "Mystic Garden", glassware: "Martini, Jewelry Box", method: "Shake & Strain",
    flavorTags: ["Herbal", "Honey", "Yuzu", "Smoke"],
    ingredients: ["1.5 oz The Botanist Gin", "0.5 oz Cointreau Orange Liqueur", "0.5 oz Finest Call Single Pressed Lemon Juice", "0.5 oz Sweetbird Honeycomb Syrup", "2 oz Fever Tree Lime Yuzu Soda", "4 Basil Leaves (torn in half)"],
    garnish: "Basil and/or Mint Sprig, Dehydrated Lavender, Lemon Wheel, Flavored Smoke",
    directions: "Combine all ingredients (except Fever Tree) in a cocktail shaker with ice. Shake and strain into martini glass. Top with Fever Tree Lime Yuzu Soda. Garnish and fill bottom drawer with flavored smoke. Open tableside to release smoke and inform guest of interactive self garnish.",
    prep: "", funFact: "The Botanist Gin is distilled on Islay — an island better known for smoky whisky — using a large number of hand-foraged local botanicals alongside the classic nine.", bestFor: "The guest who wants a show: the smoke-filled drawer is a genuine tableside moment."
  },
  {
    id: "c6", name: "Scottish Manhattan", glassware: "Martini", method: "Stir & Strain",
    flavorTags: ["Malt", "Dried Fruit", "Baking Spice", "Bitters"],
    ingredients: ["2 oz Glenfiddich 12yr Single Malt", "1 oz Martini & Rossi Sweet Vermouth", "2 Dashes Angostura Bitters"],
    garnish: "Cherry",
    directions: "Combine all ingredients into mixing glass with ice. Stir and strain into martini glass. Garnish and serve.",
    prep: "", funFact: "Glenfiddich means &ldquo;Valley of the Deer&rdquo; in Gaelic, and it's been one of the world's best-selling single malts for decades.", bestFor: "A Manhattan drinker who wants something smoky and malty instead of the usual bourbon or rye base."
  },
  {
    id: "c7", name: "Jade in the Shade", glassware: "Coupe", method: "Shake & Strain",
    flavorTags: ["Matcha", "Mint", "Lime", "Silky"],
    ingredients: ["2 oz Roku Gin", "1.5 oz Mint Matcha Syrup (house prep)", "1 oz Finest Call Single Pressed Lime Juice", "1 oz Egg White"],
    garnish: "Mint Leaf, Matcha Chocolate Shavings",
    directions: "Combine all ingredients in a cocktail shaker with ice. Shake and strain into coupe glass. Garnish and serve.",
    prep: "Mint Matcha Syrup: whisk 1 bottle (33 oz) Sweetbird Mojito Mint Syrup with 2 tbsp high grade matcha powder until fully suspended. Label, date, refrigerate.", funFact: "Matcha has been central to Japanese tea ceremony for centuries — prized as much for the ritual as the flavor.", bestFor: "A guest who wants something visually striking and less sweet than a typical shaken cocktail."
  },
  {
    id: "c8", name: "Gilded Goose", glassware: "Martini, Martini Tray Set (optional)", method: "Shake & Strain",
    flavorTags: ["Briny", "Olive", "Dry", "Crisp"],
    ingredients: ["2.5 oz Grey Goose Vodka", "0.5 oz Martini & Rossi Dry Vermouth", "0.5 oz Olive Brine"],
    garnish: "3 Skewered Olives, Fries (optional)",
    directions: "Combine vodka, vermouth, and olive brine into a shaker tin. Shake with ice and double strain into a chilled martini glass. Garnish and serve.",
    prep: "", funFact: "The dirty martini's olive brine has been used to cut vodka's neutrality since the drink's classic era.", bestFor: "A savory-forward guest who finds sweeter cocktails uninteresting."
  },
  {
    id: "c9", name: "Cosmobelle", glassware: "Coupe", method: "Shake & Strain",
    flavorTags: ["Cranberry", "Citrus", "Dragon Fruit", "Sweet-Tart"],
    ingredients: ["1.5 oz Absolut Citron", "0.5 oz Cointreau Orange Liqueur", "1.5 oz Cranberry Juice", "0.5 oz Finest Call Single Pressed Lime Juice", "0.5 oz Sweetbird Dragon Fruit & Papaya Syrup"],
    garnish: "Dehydrated Dragon Fruit, Gold Sugar Half Rim",
    directions: "Combine all ingredients in a cocktail shaker with ice. Shake and strain into coupe glass. Garnish and serve.",
    prep: "", funFact: "A modern riff on the 1990s Cosmopolitan — dragon fruit and papaya syrup update the classic citrus-cranberry formula.", bestFor: "A guest who loved Cosmos in their heyday and wants a fresher take."
  },
  {
    id: "c10", name: "Gold Fashioned", glassware: "Single Rocks Glass", method: "Stir & Strain",
    flavorTags: ["Whiskey", "Cabernet", "Oak Spice", "Bitters"],
    ingredients: ["1.5 oz Jameson Irish Whiskey", "0.5 oz WhistlePig PiggyBack 6yr Rye", "0.25 oz Cabernet Simple Syrup (house prep)", "2 Dashes Angostura Bitters"],
    garnish: "Manicured Orange Peel, Luxardo Cherry, 24k Large Gold Flakes",
    directions: "Combine all ingredients into a mixing glass with ice. Stir and strain into single rocks glass over large format ice. Garnish and serve.",
    prep: "Cabernet Simple Syrup: blend 1 bottle (25 oz) house Cabernet with 40 oz white sugar on medium for 5 minutes until fully dissolved and smooth. Label, date, store chilled. Yields ~66 oz.", funFact: "Pairing Irish whiskey with rye is unusual — Jameson's smoothness balances the spice WhistlePig's rye brings to the blend.", bestFor: "An Old Fashioned drinker who wants something a touch sweeter and more layered."
  },
  {
    id: "c11", name: "Golden 'B'", glassware: "Martini", method: "Shake & Strain",
    flavorTags: ["Honey", "Lemon", "Bourbon", "Sparkling"],
    ingredients: ["1.5 oz Maker's Mark Bourbon", "1 oz Finest Call Single Pressed Lemon Juice", "0.75 oz Gold Glitter Honeycomb Syrup (house prep)", "2 oz Sparkling Wine"],
    garnish: "Dehydrated Lemon Wheel, Gold Sugar Stripe",
    directions: "Combine all ingredients (minus sparkling wine) into a shaker tin. Shake with ice and strain into a martini glass. Top with sparkling wine. Garnish and serve.",
    prep: "Gold Glitter Honeycomb Syrup: whisk 1 bottle (33 oz) Sweetbird Honeycomb Syrup with 2.5 g edible gold luster dust until fully suspended. Label, date. Yields 33 oz.", funFact: "Most whiskey sours lean on egg white for texture; this one skips it and lightens things with sparkling wine instead.", bestFor: "A celebratory, bourbon-curious guest who wants something festive rather than a standard sour."
  },
  {
    id: "c12", name: "Opulent Espresso Martini", glassware: "Coupe", method: "Shake & Strain",
    flavorTags: ["Espresso", "Vanilla", "Agave", "Roasted"],
    ingredients: ["1.5 oz Vanilla Bean Infused Patr\u00f3n Reposado (house prep)", "0.5 oz Mr. Black Cold Brew Liqueur", "2.5 oz Berg House Espresso Martini Mix (house prep)"],
    garnish: "Three Gold Dusted Espresso Beans",
    directions: "Combine all ingredients into a shaker tin. Shake with ice and strain into a coupe glass. Garnish and serve.",
    prep: "Vanilla Bean Patr\u00f3n: drop 2 split vanilla pods into a Patr\u00f3n Reposado bottle to infuse on the backbar; keep at least 2 infused bottles on hand. Espresso Martini Mix: dissolve 1 can (94g) Illy Instant Classico into 40 oz warm water, add 24 oz Maven Cold Brew and 1 bottle (33.8 oz) Sweetbird Vanilla Syrup, stir. Label, date, chill. Yields 64 oz.", funFact: "Patrón Reposado rests in oak for several months before bottling, giving it a rounder character than blanco tequila — an unusual espresso martini base in place of vodka.", bestFor: "Dessert-course energy — a coffee lover who wants their after-dinner drink to double as dessert."
  }
];
